---
title: "au-merchant-waterfall"
author: "Kuljeet"
date: "10/27/2023"
output: html_document
---


```{r, warning=FALSE,message=FALSE,include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(DBI)
library(dplyr)
library(dbplyr)
library(odbc)
library(DT)
library(tidyverse)
library(data.table)
library(waterfalls)
library(ggplot2)
library(janitor)
library(scales)
library(sqldf)
library(ggthemes)
library(plyr)
library(knitr)
library(stringr)

```


```{r}
readRenviron(".Renviron") 


database <- "PD_CUSTOMER_ANALYTICS"
myconn <- DBI::dbConnect(odbc::odbc(), "SNOWFLAKEC360", 
                         database = "PD_CUSTOMER_ANALYTICS", 
                         uid = if(Sys.getenv('SNOWFLAKE_UID') != "") Sys.getenv('SNOWFLAKE_UID') else NULL,
                         token = if(Sys.getenv('SNOWFLAKE_C360_TOKEN') != "") Sys.getenv('SNOWFLAKE_C360_TOKEN') else NULL)

```

```{sql connection=myconn, output.var = "AU_MKT_BASE"}

SELECT 
  X1.CUST_ACCT_APPL_ID
  ,X1.CRM_PRODUCT
  ,X1.CRM_ACCOUNT_ACTIVE_FLAG
   ,X1.FIRST_NAME
  ,X1.EMAILADDRESS
  ,X3.STATUSCURR
  ,X1.GENDER
  ,X3.CRM_MOB
  ,ROUND(X1.CREDITLIMIT_AMT) AS CREDITLIMIT
  ,X1.CURR_BAL_AMT
  ,X3.CRM_OTB_AMT
  ,X2.MARKETABLE_CARDS_FLAG
  ,X2.DNS_CLVLE_DIGITAL_FLAG 
  ,X2.ACMA_OPTIN 
  ,X2.SPAMHAUS_OPTIN 
  ,X3.TOP_DEALER_NAME
  ,CASE WHEN ((X1.CREDITLIMIT_AMT - X1.CURR_BAL_AMT < 500)) THEN 1 ELSE 0 END AS OTB_LESSTHAN_1000
  ,CASE WHEN (X1.FIRST_NAME IS NULL or X1.EMAILADDRESS IS NULL) THEN 1 ELSE 0 END AS IF_MISSING_CONTACT
  ,CASE WHEN X2.MARKETABLE_CARDS_FLAG != 'Y' OR X2.DNS_CLVLE_DIGITAL_FLAG != 'I' THEN 1 ELSE 0 END AS IF_NOT_MARKETABLE_FLAG
  ,CASE WHEN (X2.ACMA_OPTIN = 'I' ) then 0 else 1 end as IF_ACMA_FLAG
  ,CASE WHEN (X2.SPAMHAUS_OPTIN = 'I') then 0 else 1 end as IF_SPAMHAUS_FLAG
  ,CASE WHEN X3.TOP_DEALER_NAME IN ('Harvey Norman') THEN 1 ELSE 0 END AS IF_HN_ORIG
  ,CASE WHEN X3.TOP_DEALER_NAME IN ('Apple') THEN 1 ELSE 0 END AS IF_APPLE_ORIG
  ,CASE WHEN X3.TOP_DEALER_NAME IN ('Amart Furniture') THEN 1 ELSE 0 END AS IF_AMART_ORIG
  ,CASE WHEN X3.TOP_DEALER_NAME IN ('Ashley Furniture Group') THEN 1 ELSE 0 END AS IF_ASHLEYFURNITURE_ORIG
  ,CASE WHEN X3.TOP_DEALER_NAME IN ('Bed Shed') THEN 1 ELSE 0 END AS IF_BEDSHED_ORIG
  ,CASE WHEN X3.TOP_DEALER_NAME IN ('Beds N Dreams') THEN 1 ELSE 0 END AS IF_BEDNDREAMS_ORIG
  ,CASE WHEN X3.TOP_DEALER_NAME IN ('Eureka Street') THEN 1 ELSE 0 END AS IF_EUREKASTREET_ORIG
  ,CASE WHEN X3.TOP_DEALER_NAME IN ('Forty Winks') THEN 1 ELSE 0 END AS IF_FORTYWINKS_ORIG
  ,CASE WHEN X3.TOP_DEALER_NAME IN ('Freedom') THEN 1 ELSE 0 END AS IF_FREEDOM_ORIG
   ,CASE WHEN X3.TOP_DEALER_NAME IN ('Johnny?s Furniture Group') THEN 1 ELSE 0 END AS IF_JOHNYSFURNITURE_ORIG
   ,CASE WHEN X3.TOP_DEALER_NAME IN ('Sleeping Giant') THEN 1 ELSE 0 END AS IF_SLEEPINGGIANT_ORIG
   ,CASE WHEN X3.TOP_DEALER_NAME IN ('Snooze') THEN 1 ELSE 0 END AS IF_SNOOZE_ORIG
   --
   ,CASE WHEN X3.TOP_DEALER_NAME IN ('Bing Lee') THEN 1 ELSE 0 END AS IF_BINGLEE_ORIG
   ,CASE WHEN X3.TOP_DEALER_NAME IN ('Circles.Life Online') THEN 1 ELSE 0 END AS IF_CIRCLESLIFEONLINE_ORIG
   ,CASE WHEN X3.TOP_DEALER_NAME IN ('Dell') THEN 1 ELSE 0 END AS IF_DELL_ORIG
   ,CASE WHEN X3.TOP_DEALER_NAME IN ('Ingram Micro') THEN 1 ELSE 0 END AS IF_INGRAMMICRO_ORIG
   ,CASE WHEN X3.TOP_DEALER_NAME IN ('JB Hi Fi') THEN 1 ELSE 0 END AS IF_JB_HI_FI_ORIG 
   ,CASE WHEN X3.TOP_DEALER_NAME IN ('Lenovo') THEN 1 ELSE 0 END AS IF_LENOVO_ORIG 
   ,CASE WHEN X3.TOP_DEALER_NAME IN ('Reebelo Australia Pty Ltd') THEN 1 ELSE 0 END AS IF_REEBELO_ORIG 
   ,CASE WHEN X3.TOP_DEALER_NAME IN ('Samsung Electronics Australia') THEN 1 ELSE 0 END AS IF_SAMSUNG_ORIG
   ,CASE WHEN X3.TOP_DEALER_NAME IN ('The Good Guys') THEN 1 ELSE 0 END AS IF_THE_GOOD_GUYS_ORIG
  ,CASE WHEN (X4.RP_12M_PROGRAM_CONTROL = 'Y' OR X4.RP_12M_EMAIL_CONTROL = 'Y') THEN 1 ELSE 0 END AS IF_PROG_EMAIL_RP_CONTROL
  FROM 
"PD_CUSTOMER_ANALYTICS"."CUSTOMER_ANALYTICS"."TBL_DM_ACCT_DETAILS" X1 
INNER JOIN "PD_CUSTOMER_ANALYTICS"."CUSTOMER_ANALYTICS"."TBL_DM_ACCT_ELIGIBILITY" X2
ON X1.CUST_ACCT_APPL_ID = X2.CUST_ACCT_APPL_ID 
LEFT JOIN "PD_CUSTOMER_ANALYTICS"."CUSTOMER_ANALYTICS"."TBL_DM_ACCT_CARD" X3
ON X1.CUST_ACCT_APPL_ID = X3.CUST_ACCT_APPL_ID 
LEFT JOIN "INTEG_RESPONSYS"."CAMPAIGN_PLCARDS"."PET_CARDS_CUSTOMER" X4
ON X1.CUST_ACCT_APPL_ID = X4.CUST_ACCT_APPL_ID 
WHERE X1.CRM_PRODUCT in ('GEMV','CL','BE') AND X1.CRM_ACCOUNT_ACTIVE_FLAG >= 0.5
        
```

```{r}
# AU_MKT_BASE %>% dplyr::count(CRM_ACCOUNT_ACTIVE_FLAG,)

# AU_MKT_BASE %>% dplyr::count(IF_NOT_MARKETABLE_FLAG,MARKETABLE_CARDS_FLAG,DNS_CLVLE_DIGITAL_FLAG)

# AU_MKT_BASE %>% dplyr::count(IF_ACMA_FLAG,ACMA_OPTIN)

# AU_MKT_BASE %>% dplyr::count(SPAMHAUS_OPTIN,ACMA_OPTIN,IF_SPAMHAUS_FLAG,IF_ACMA_FLAG)
 
# AU_MKT_BASE %>% dplyr::count(IF_HN_ORIG)

# AU_MKT_BASE %>% dplyr::count(OTB_LESSTHAN_1000)

 #AU_MKT_BASE %>% dplyr::count(IF_NOT_MARKETABLE_FLAG,IF_THE_GOOD_GUYS_ORIG,)

```

# Results {.tabset}
## Furniture-Bedding-edm

```{r}

AU_Merchant_Waterfall <- AU_MKT_BASE %>% 
  mutate(DROPOUT_FLAG = case_when(
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_MISSING_CONTACT == 0  & IF_ACMA_FLAG == 0 
     & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0  & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 &  IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 0 & IF_SLEEPINGGIANT_ORIG == 0 & IF_SNOOZE_ORIG == 0 ) ~ 'Total Passed Wash',
    ( IF_NOT_MARKETABLE_FLAG == 1) ~ '01.NON-MARKETABLE-AND-DNS-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 1 ) ~ '02.ACMA-FLAG-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 1 ) ~ '03.MISSING-CONTACT-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 1) ~ '04.HN-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 1) ~ '05.APPLE-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 1) ~ '06.AMART-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 1) ~ '07.AshleyFurniture-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 1) ~ '08.BEDSHED-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG ==1) ~ '09.BEDnDREAMS-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 1 ) ~ '10.EurekaStreet-ORGINATED-EXCL',
   (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG ==1 ) ~ '11.FortyWinks-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 1 ) ~ '12.Freedom-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 1 ) ~ '13.JohnysFurniture-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 0 & IF_SLEEPINGGIANT_ORIG == 1 ) ~ '14.SleepingGiant-ORGINATED-EXCL',
   (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 0 & IF_SLEEPINGGIANT_ORIG == 1 ) ~ '15.SleepingGiant-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 0 & IF_SLEEPINGGIANT_ORIG == 0 & IF_SNOOZE_ORIG == 1) ~ '16.Snooze-ORGINATED-EXCL',
  )) 

##GEMVNZ_waterfall %>% dplyr::count(DROPOUT_FLAG)

AU_Merchant_Waterfall_t <- AU_Merchant_Waterfall %>%  group_by(DROPOUT_FLAG) %>% dplyr::summarise(T_num = n())%>% arrange(desc(DROPOUT_FLAG))

au_merchant_table <- AU_Merchant_Waterfall %>%  group_by(DROPOUT_FLAG) %>% dplyr::summarise(T_NUM = format(n(),big.mark = ",", scientific = FALSE))%>% arrange(DROPOUT_FLAG)
au_merchant_table_t1 <- as.data.frame(au_merchant_table)%>% arrange(DROPOUT_FLAG)


##str(GEMVNZ_t1)

waterfall(AU_Merchant_Waterfall_t, calc_total = TRUE, total_axis_text = "GEMV-CL-BE-TOTAL-OPEN-BASE",total_rect_color = "goldenrod1", total_rect_text_color = "black" )+coord_flip()+
  labs(title = "Waterfall Report for GEMV-CL-BE ", 
       subtitle = "Total MARKETABLE", 
       x = "",
       y = "")+theme_minimal()

kable(au_merchant_table_t1)
t <- datatable(
  au_merchant_table_t1, rownames = FALSE,
  extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = c('excel')
  )
)
```

```{r}
gemv_Merchant_Waterfall <- AU_MKT_BASE %>% 
  filter(CRM_PRODUCT == 'GEMV')%>%
  mutate(DROPOUT_FLAG = case_when(
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_MISSING_CONTACT == 0  & IF_ACMA_FLAG == 0 
     & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0  & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 &  IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 0 & IF_SLEEPINGGIANT_ORIG == 0 & IF_SNOOZE_ORIG == 0 ) ~ 'Total Passed Wash',
    ( IF_NOT_MARKETABLE_FLAG == 1) ~ '01.NON-MARKETABLE-AND-DNS-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 1 ) ~ '02.ACMA-FLAG-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 1 ) ~ '03.MISSING-CONTACT-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 1) ~ '04.HN-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 1) ~ '05.APPLE-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 1) ~ '06.AMART-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 1) ~ '07.AshleyFurniture-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 1) ~ '08.BEDSHED-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG ==1) ~ '09.BEDnDREAMS-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 1 ) ~ '10.EurekaStreet-ORGINATED-EXCL',
   (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG ==1 ) ~ '11.FortyWinks-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 1 ) ~ '12.Freedom-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 1 ) ~ '13.JohnysFurniture-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 0 & IF_SLEEPINGGIANT_ORIG == 1 ) ~ '14.SleepingGiant-ORGINATED-EXCL',
   (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 0 & IF_SLEEPINGGIANT_ORIG == 1 ) ~ '15.SleepingGiant-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 0 & IF_SLEEPINGGIANT_ORIG == 0 & IF_SNOOZE_ORIG == 1) ~ '16.Snooze-ORGINATED-EXCL',
  )) 

##GEMVNZ_waterfall %>% dplyr::count(DROPOUT_FLAG)

gemv_Merchant_Waterfall_t <- gemv_Merchant_Waterfall %>%  group_by(DROPOUT_FLAG) %>% dplyr::summarise(T_num = n())%>% arrange(desc(DROPOUT_FLAG))

gemv_merchant_table <- gemv_Merchant_Waterfall %>%  group_by(DROPOUT_FLAG) %>% dplyr::summarise(T_NUM = format(n(),big.mark = ",", scientific = FALSE))%>% arrange(DROPOUT_FLAG)
gemv_merchant_table_t1 <- as.data.frame(gemv_merchant_table)%>% arrange(DROPOUT_FLAG)


##str(GEMVNZ_t1)

waterfall(gemv_Merchant_Waterfall_t, calc_total = TRUE, total_axis_text = "GEMV-OPEN-BASE",total_rect_color = "light green", total_rect_text_color = "black" )+coord_flip()+
  labs(title = "Waterfall Report for GEMV ", 
       subtitle = "Total MARKETABLE", 
       x = "",
       y = "")+theme_minimal()

kable(gemv_merchant_table_t1)
t <- datatable(
  gemv_merchant_table_t1, rownames = FALSE,
  extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = c('excel')
  )
)
```


```{r}
cl_Merchant_Waterfall <- AU_MKT_BASE %>% 
  filter(CRM_PRODUCT == 'CL')%>%
  mutate(DROPOUT_FLAG = case_when(
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_MISSING_CONTACT == 0  & IF_ACMA_FLAG == 0 
     & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0  & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 &  IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 0 & IF_SLEEPINGGIANT_ORIG == 0 & IF_SNOOZE_ORIG == 0 ) ~ 'Total Passed Wash',
    ( IF_NOT_MARKETABLE_FLAG == 1) ~ '01.NON-MARKETABLE-AND-DNS-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 1 ) ~ '02.ACMA-FLAG-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 1 ) ~ '03.MISSING-CONTACT-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 1) ~ '04.HN-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 1) ~ '05.APPLE-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 1) ~ '06.AMART-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 1) ~ '07.AshleyFurniture-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 1) ~ '08.BEDSHED-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG ==1) ~ '09.BEDnDREAMS-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 1 ) ~ '10.EurekaStreet-ORGINATED-EXCL',
   (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG ==1 ) ~ '11.FortyWinks-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 1 ) ~ '12.Freedom-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 1 ) ~ '13.JohnysFurniture-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 0 & IF_SLEEPINGGIANT_ORIG == 1 ) ~ '14.SleepingGiant-ORGINATED-EXCL',
   (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 0 & IF_SLEEPINGGIANT_ORIG == 1 ) ~ '15.SleepingGiant-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 0 & IF_SLEEPINGGIANT_ORIG == 0 & IF_SNOOZE_ORIG == 1) ~ '16.Snooze-ORGINATED-EXCL',
  )) 

##GEMVNZ_waterfall %>% dplyr::count(DROPOUT_FLAG)

cl_Merchant_Waterfall_t <- cl_Merchant_Waterfall %>%  group_by(DROPOUT_FLAG) %>% dplyr::summarise(T_num = n())%>% arrange(desc(DROPOUT_FLAG))

cl_merchant_table <- cl_Merchant_Waterfall %>%  group_by(DROPOUT_FLAG) %>% dplyr::summarise(T_NUM = format(n(),big.mark = ",", scientific = FALSE))%>% arrange(DROPOUT_FLAG)
cl_merchant_table_t1 <- as.data.frame(cl_merchant_table)%>% arrange(DROPOUT_FLAG)


##str(GEMVNZ_t1)

waterfall(cl_Merchant_Waterfall_t, calc_total = TRUE, total_axis_text = "CL-OPEN-BASE",total_rect_color = "pink", total_rect_text_color = "black" )+coord_flip()+
  labs(title = "Waterfall Report for CL ", 
       subtitle = "Total MARKETABLE", 
       x = "",
       y = "")+theme_minimal()

kable(cl_merchant_table_t1)
t <- datatable(
  cl_merchant_table_t1, rownames = FALSE,
  extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = c('excel')
  )
)
```


```{r}
be_Merchant_Waterfall <- AU_MKT_BASE %>% 
  filter(CRM_PRODUCT == 'BE')%>%
  mutate(DROPOUT_FLAG = case_when(
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_MISSING_CONTACT == 0  & IF_ACMA_FLAG == 0 
     & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0  & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 &  IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 0 & IF_SLEEPINGGIANT_ORIG == 0 & IF_SNOOZE_ORIG == 0 ) ~ 'Total Passed Wash',
    ( IF_NOT_MARKETABLE_FLAG == 1) ~ '01.NON-MARKETABLE-AND-DNS-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 1 ) ~ '02.ACMA-FLAG-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 1 ) ~ '03.MISSING-CONTACT-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 1) ~ '04.HN-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 1) ~ '05.APPLE-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 1) ~ '06.AMART-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 1) ~ '07.AshleyFurniture-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 1) ~ '08.BEDSHED-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG ==1) ~ '09.BEDnDREAMS-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 1 ) ~ '10.EurekaStreet-ORGINATED-EXCL',
   (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG ==1 ) ~ '11.FortyWinks-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 1 ) ~ '12.Freedom-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 1 ) ~ '13.JohnysFurniture-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 0 & IF_SLEEPINGGIANT_ORIG == 1 ) ~ '14.SleepingGiant-ORGINATED-EXCL',
   (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 0 & IF_SLEEPINGGIANT_ORIG == 1 ) ~ '15.SleepingGiant-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_AMART_ORIG == 0 & IF_ASHLEYFURNITURE_ORIG == 0 & IF_BEDSHED_ORIG == 0 & IF_BEDNDREAMS_ORIG == 0 & IF_EUREKASTREET_ORIG == 0 & IF_FORTYWINKS_ORIG == 0 & IF_FREEDOM_ORIG == 0 & IF_JOHNYSFURNITURE_ORIG == 0 & IF_SLEEPINGGIANT_ORIG == 0 & IF_SNOOZE_ORIG == 1) ~ '16.Snooze-ORGINATED-EXCL',
  )) 

##GEMVNZ_waterfall %>% dplyr::count(DROPOUT_FLAG)

be_Merchant_Waterfall_t <- be_Merchant_Waterfall %>%  group_by(DROPOUT_FLAG) %>% dplyr::summarise(T_num = n())%>% arrange(desc(DROPOUT_FLAG))

be_merchant_table <- be_Merchant_Waterfall %>%  group_by(DROPOUT_FLAG) %>% dplyr::summarise(T_NUM = format(n(),big.mark = ",", scientific = FALSE))%>% arrange(DROPOUT_FLAG)
be_merchant_table_t1 <- as.data.frame(be_merchant_table)%>% arrange(DROPOUT_FLAG)


##str(GEMVNZ_t1)

waterfall(be_Merchant_Waterfall_t, calc_total = TRUE, total_axis_text = "BE-TOTAL-OPEN-BASE",total_rect_color = "purple", total_rect_text_color = "black" )+coord_flip()+
  labs(title = "Waterfall Report for BE ", 
       subtitle = "Total MARKETABLE", 
       x = "",
       y = "")+theme_minimal()

kable(be_merchant_table_t1)
t <- datatable(
  be_merchant_table_t1, rownames = FALSE,
  extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = c('excel')
  )
)
```




## Electrical-Computer-edm

```{r}

AU_Merchant_Waterfall_NEXT <- AU_MKT_BASE %>% 
  mutate(DROPOUT_FLAG = case_when(
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_MISSING_CONTACT == 0  & IF_ACMA_FLAG == 0 
     & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG == 0  & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG  == 0 & IF_JB_HI_FI_ORIG == 0 & IF_LENOVO_ORIG == 0 &  IF_REEBELO_ORIG == 0 & IF_SAMSUNG_ORIG == 0 & IF_THE_GOOD_GUYS_ORIG == 0 ) ~ 'Total Passed Wash',
    ( IF_NOT_MARKETABLE_FLAG == 1) ~ '01.NON-MARKETABLE-AND-DNS-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 1 ) ~ '02.ACMA-FLAG-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 1 ) ~ '03.MISSING-CONTACT-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 1) ~ '04.HN-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 1) ~ '05.APPLE-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 1) ~ '06.BINGLEE-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 1) ~ '07.CIRCLESLIFEONLINE-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 1) ~ '08.DELL-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 1) ~ '09.INGRAMMICRO-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 1 ) ~ '10.JBHIFI-ORGINATED-EXCL',
   (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 0 & IF_LENOVO_ORIG  ==1 ) ~ '11.LENOVO-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 0 & IF_LENOVO_ORIG  ==0 &  IF_REEBELO_ORIG  == 1 ) ~ '12.REEBELO-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 0 & IF_LENOVO_ORIG  ==0 &  IF_REEBELO_ORIG  == 0 & IF_SAMSUNG_ORIG == 1 ) ~ '13.SAMSUNG-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 0 & IF_LENOVO_ORIG  ==0 &  IF_REEBELO_ORIG  == 0 & IF_SAMSUNG_ORIG == 0 & IF_THE_GOOD_GUYS_ORIG  == 1 ) ~ '14.THEGOODGUYS-ORGINATED-EXCL',
  )) 

##GEMVNZ_waterfall %>% dplyr::count(DROPOUT_FLAG)

AU_Merchant_Waterfall_next_t <- AU_Merchant_Waterfall_NEXT %>%  group_by(DROPOUT_FLAG) %>% dplyr::summarise(T_num = n())%>% arrange(desc(DROPOUT_FLAG))

au_merchant_table_next <- AU_Merchant_Waterfall_NEXT %>%  group_by(DROPOUT_FLAG) %>% dplyr::summarise(T_NUM = format(n(),big.mark = ",", scientific = FALSE))%>% arrange(DROPOUT_FLAG)
au_merchant_table_next_t1 <- as.data.frame(au_merchant_table_next)%>% arrange(DROPOUT_FLAG)


##str(GEMVNZ_t1)

waterfall(AU_Merchant_Waterfall_next_t, calc_total = TRUE, total_axis_text = "GEMV-CL-BE-TOTAL-OPEN-BASE",total_rect_color = "goldenrod1", total_rect_text_color = "black" )+coord_flip()+
  labs(title = "Waterfall Report for GEMV-CL-BE ", 
       subtitle = "Total MARKETABLE", 
       x = "",
       y = "")+theme_minimal()

kable(au_merchant_table_next_t1)
t <- datatable(
  au_merchant_table_next_t1, rownames = FALSE,
  extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = c('excel')
  )
)
```

```{r}

gemv_Merchant_Waterfall_NEXT <- AU_MKT_BASE %>% 
  filter(CRM_PRODUCT == 'GEMV') %>%
  mutate(DROPOUT_FLAG = case_when(
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_MISSING_CONTACT == 0  & IF_ACMA_FLAG == 0 
     & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG == 0  & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG  == 0 & IF_JB_HI_FI_ORIG == 0 & IF_LENOVO_ORIG == 0 &  IF_REEBELO_ORIG == 0 & IF_SAMSUNG_ORIG == 0 & IF_THE_GOOD_GUYS_ORIG == 0 ) ~ 'Total Passed Wash',
    ( IF_NOT_MARKETABLE_FLAG == 1) ~ '01.NON-MARKETABLE-AND-DNS-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 1 ) ~ '02.ACMA-FLAG-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 1 ) ~ '03.MISSING-CONTACT-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 1) ~ '04.HN-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 1) ~ '05.APPLE-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 1) ~ '06.BINGLEE-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 1) ~ '07.CIRCLESLIFEONLINE-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 1) ~ '08.DELL-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 1) ~ '09.INGRAMMICRO-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 1 ) ~ '10.JBHIFI-ORGINATED-EXCL',
   (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 0 & IF_LENOVO_ORIG  ==1 ) ~ '11.LENOVO-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 0 & IF_LENOVO_ORIG  ==0 &  IF_REEBELO_ORIG  == 1 ) ~ '12.REEBELO-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 0 & IF_LENOVO_ORIG  ==0 &  IF_REEBELO_ORIG  == 0 & IF_SAMSUNG_ORIG == 1 ) ~ '13.SAMSUNG-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 0 & IF_LENOVO_ORIG  ==0 &  IF_REEBELO_ORIG  == 0 & IF_SAMSUNG_ORIG == 0 & IF_THE_GOOD_GUYS_ORIG  == 1 ) ~ '14.THEGOODGUYS-ORGINATED-EXCL',
  )) 

##GEMVNZ_waterfall %>% dplyr::count(DROPOUT_FLAG)

gemv_Merchant_Waterfall_next_t <- gemv_Merchant_Waterfall_NEXT %>%  group_by(DROPOUT_FLAG) %>% dplyr::summarise(T_num = n())%>% arrange(desc(DROPOUT_FLAG))

gemv_merchant_table_next <- gemv_Merchant_Waterfall_NEXT %>%  group_by(DROPOUT_FLAG) %>% dplyr::summarise(T_NUM = format(n(),big.mark = ",", scientific = FALSE))%>% arrange(DROPOUT_FLAG)
gemv_merchant_table_next_t1 <- as.data.frame(gemv_merchant_table_next)%>% arrange(DROPOUT_FLAG)


##str(GEMVNZ_t1)

waterfall(gemv_Merchant_Waterfall_next_t, calc_total = TRUE, total_axis_text = "GEMV-OPEN-BASE",total_rect_color = "light green", total_rect_text_color = "black" )+coord_flip()+
  labs(title = "Waterfall Report for GEMV ", 
       subtitle = "Total MARKETABLE", 
       x = "",
       y = "")+theme_minimal()

kable(gemv_merchant_table_next_t1)
t <- datatable(
  gemv_merchant_table_next_t1, rownames = FALSE,
  extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = c('excel')
  )
)
```

```{r}

cl_Merchant_Waterfall_NEXT <- AU_MKT_BASE %>% 
  filter(CRM_PRODUCT == 'CL') %>%
  mutate(DROPOUT_FLAG = case_when(
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_MISSING_CONTACT == 0  & IF_ACMA_FLAG == 0 
     & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG == 0  & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG  == 0 & IF_JB_HI_FI_ORIG == 0 & IF_LENOVO_ORIG == 0 &  IF_REEBELO_ORIG == 0 & IF_SAMSUNG_ORIG == 0 & IF_THE_GOOD_GUYS_ORIG == 0 ) ~ 'Total Passed Wash',
    ( IF_NOT_MARKETABLE_FLAG == 1) ~ '01.NON-MARKETABLE-AND-DNS-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 1 ) ~ '02.ACMA-FLAG-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 1 ) ~ '03.MISSING-CONTACT-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 1) ~ '04.HN-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 1) ~ '05.APPLE-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 1) ~ '06.BINGLEE-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 1) ~ '07.CIRCLESLIFEONLINE-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 1) ~ '08.DELL-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 1) ~ '09.INGRAMMICRO-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 1 ) ~ '10.JBHIFI-ORGINATED-EXCL',
   (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 0 & IF_LENOVO_ORIG  ==1 ) ~ '11.LENOVO-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 0 & IF_LENOVO_ORIG  ==0 &  IF_REEBELO_ORIG  == 1 ) ~ '12.REEBELO-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 0 & IF_LENOVO_ORIG  ==0 &  IF_REEBELO_ORIG  == 0 & IF_SAMSUNG_ORIG == 1 ) ~ '13.SAMSUNG-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 0 & IF_LENOVO_ORIG  ==0 &  IF_REEBELO_ORIG  == 0 & IF_SAMSUNG_ORIG == 0 & IF_THE_GOOD_GUYS_ORIG  == 1 ) ~ '14.THEGOODGUYS-ORGINATED-EXCL',
  )) 

##GEMVNZ_waterfall %>% dplyr::count(DROPOUT_FLAG)

cl_Merchant_Waterfall_next_t <- cl_Merchant_Waterfall_NEXT %>%  group_by(DROPOUT_FLAG) %>% dplyr::summarise(T_num = n())%>% arrange(desc(DROPOUT_FLAG))

cl_merchant_table_next <- cl_Merchant_Waterfall_NEXT %>%  group_by(DROPOUT_FLAG) %>% dplyr::summarise(T_NUM = format(n(),big.mark = ",", scientific = FALSE))%>% arrange(DROPOUT_FLAG)
cl_merchant_table_next_t1 <- as.data.frame(cl_merchant_table_next)%>% arrange(DROPOUT_FLAG)


##str(GEMVNZ_t1)

waterfall(cl_Merchant_Waterfall_next_t, calc_total = TRUE, total_axis_text = "CL-OPEN-BASE",total_rect_color = "pink", total_rect_text_color = "black" )+coord_flip()+
  labs(title = "Waterfall Report for CL ", 
       subtitle = "Total MARKETABLE", 
       x = "",
       y = "")+theme_minimal()

kable(cl_merchant_table_next_t1)
t <- datatable(
  cl_merchant_table_next_t1, rownames = FALSE,
  extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = c('excel')
  )
)
```

```{r}

be_Merchant_Waterfall_NEXT <- AU_MKT_BASE %>% 
  filter(CRM_PRODUCT == 'BE') %>%
  mutate(DROPOUT_FLAG = case_when(
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_MISSING_CONTACT == 0  & IF_ACMA_FLAG == 0 
     & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG == 0  & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG  == 0 & IF_JB_HI_FI_ORIG == 0 & IF_LENOVO_ORIG == 0 &  IF_REEBELO_ORIG == 0 & IF_SAMSUNG_ORIG == 0 & IF_THE_GOOD_GUYS_ORIG == 0 ) ~ 'Total Passed Wash',
    ( IF_NOT_MARKETABLE_FLAG == 1) ~ '01.NON-MARKETABLE-AND-DNS-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 1 ) ~ '02.ACMA-FLAG-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 1 ) ~ '03.MISSING-CONTACT-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 1) ~ '04.HN-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0  & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 1) ~ '05.APPLE-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 1) ~ '06.BINGLEE-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 1) ~ '07.CIRCLESLIFEONLINE-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 1) ~ '08.DELL-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 1) ~ '09.INGRAMMICRO-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 1 ) ~ '10.JBHIFI-ORGINATED-EXCL',
   (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 0 & IF_LENOVO_ORIG  ==1 ) ~ '11.LENOVO-ORGINATED-EXCL',
    (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 0 & IF_LENOVO_ORIG  ==0 &  IF_REEBELO_ORIG  == 1 ) ~ '12.REEBELO-ORGINATED-EXCL',
 (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 0 & IF_LENOVO_ORIG  ==0 &  IF_REEBELO_ORIG  == 0 & IF_SAMSUNG_ORIG == 1 ) ~ '13.SAMSUNG-ORGINATED-EXCL',
  (IF_NOT_MARKETABLE_FLAG == 0 & IF_ACMA_FLAG == 0 & IF_MISSING_CONTACT == 0 & IF_HN_ORIG == 0 & IF_APPLE_ORIG == 0 & IF_BINGLEE_ORIG  == 0 & IF_CIRCLESLIFEONLINE_ORIG == 0 & IF_DELL_ORIG == 0 & IF_INGRAMMICRO_ORIG == 0 & IF_JB_HI_FI_ORIG  == 0 & IF_LENOVO_ORIG  ==0 &  IF_REEBELO_ORIG  == 0 & IF_SAMSUNG_ORIG == 0 & IF_THE_GOOD_GUYS_ORIG  == 1 ) ~ '14.THEGOODGUYS-ORGINATED-EXCL',
  )) 

##GEMVNZ_waterfall %>% dplyr::count(DROPOUT_FLAG)

be_Merchant_Waterfall_next_t <- be_Merchant_Waterfall_NEXT %>%  group_by(DROPOUT_FLAG) %>% dplyr::summarise(T_num = n())%>% arrange(desc(DROPOUT_FLAG))

be_merchant_table_next <- be_Merchant_Waterfall_NEXT %>%  group_by(DROPOUT_FLAG) %>% dplyr::summarise(T_NUM = format(n(),big.mark = ",", scientific = FALSE))%>% arrange(DROPOUT_FLAG)
be_merchant_table_next_t1 <- as.data.frame(be_merchant_table_next)%>% arrange(DROPOUT_FLAG)


##str(GEMVNZ_t1)

waterfall(be_Merchant_Waterfall_next_t, calc_total = TRUE, total_axis_text = "BE-OPEN-BASE",total_rect_color = "purple", total_rect_text_color = "black" )+coord_flip()+
  labs(title = "Waterfall Report for CL ", 
       subtitle = "Total MARKETABLE", 
       x = "",
       y = "")+theme_minimal()

kable(be_merchant_table_next_t1)
t <- datatable(
  be_merchant_table_next_t1, rownames = FALSE,
  extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = c('excel')
  )
)
```